# AUTOGENERATED FROM 'queries/direct_transfer_insert.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb:1234@localhost:10700 --tls-security insecure


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class DirectTransferInsertResult(NoPydanticValidation):
    id: uuid.UUID


async def direct_transfer_insert(
    executor: edgedb.AsyncIOExecutor,
    *,
    quotation_id: uuid.UUID,
    payload: str,
    user_id: uuid.UUID,
) -> DirectTransferInsertResult:
    return await executor.query_single(
        """\
        INSERT DirectTransfer {
            quotation := (SELECT Quotation FILTER .id = <std::uuid> $quotation_id),
            payload := <std::str> $payload,
            owner := (SELECT User FILTER .id = <std::uuid> $user_id),
        }\
        """,
        quotation_id=quotation_id,
        payload=payload,
        user_id=user_id,
    )
