# AUTOGENERATED FROM 'queries/job_select_one.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb:1234@localhost:10703 --tls-security insecure


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class JobSelectOneResult(NoPydanticValidation):
    id: uuid.UUID
    payer: JobSelectOneResultPayer
    title: str
    description: str
    budget_range: str | None
    categories: str | None
    approved_quotation: JobSelectOneResultApprovedQuotation | None


@dataclasses.dataclass
class JobSelectOneResultApprovedQuotation(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class JobSelectOneResultPayer(NoPydanticValidation):
    id: uuid.UUID


async def job_select_one(
    executor: edgedb.AsyncIOExecutor,
    *,
    job_id: uuid.UUID,
) -> JobSelectOneResult | None:
    return await executor.query_single(
        """\
        select default::Job {
          id,
          payer : {
            id
          },
          title,
          description,
          budget_range,
          categories,
          approved_quotation : {
            id
          }
        } filter .id = <std::uuid> $job_id\
        """,
        job_id=job_id,
    )
