# AUTOGENERATED FROM 'queries/job_insert.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb:1234@localhost:10703 --tls-security insecure


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class JobInsertResult(NoPydanticValidation):
    id: uuid.UUID


async def job_insert(
    executor: edgedb.AsyncIOExecutor,
    *,
    payer_id: uuid.UUID,
    job_title: str,
    job_description: str,
    job_budget_range: str,
    categories_json: str,
) -> JobInsertResult:
    return await executor.query_single(
        """\
        INSERT Job {
            payer := (SELECT User FILTER .id = <std::uuid> $payer_id),
            title := <std::str> $job_title,
            description := <std::str> $job_description,
            budget_range := <std::str> $job_budget_range,
            categories := <std::json> $categories_json
        }\
        """,
        payer_id=payer_id,
        job_title=job_title,
        job_description=job_description,
        job_budget_range=job_budget_range,
        categories_json=categories_json,
    )
