# AUTOGENERATED FROM 'queries/jobs_select.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb:1234@localhost:10703 --tls-security insecure


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class JobsSelectResult(NoPydanticValidation):
    id: uuid.UUID
    payer: JobsSelectResultPayer
    title: str
    description: str


@dataclasses.dataclass
class JobsSelectResultPayer(NoPydanticValidation):
    id: uuid.UUID


async def jobs_select(
    executor: edgedb.AsyncIOExecutor,
) -> list[JobsSelectResult]:
    return await executor.query(
        """\
        select default::Job {
          id,
          payer : {
            id
          },
          title,
          description
        }\
        """,
    )
