# AUTOGENERATED FROM 'queries/quotation_update_approved.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb:1234@localhost:10703 --tls-security insecure


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class QuotationUpdateApprovedResult(NoPydanticValidation):
    id: uuid.UUID


async def quotation_update_approved(
    executor: edgedb.AsyncIOExecutor,
    *,
    quotation_id: uuid.UUID,
    payer_id: uuid.UUID,
) -> QuotationUpdateApprovedResult | None:
    return await executor.query_single(
        """\
        UPDATE Quotation 
        filter .id = <std::uuid> $quotation_id and
        .state = <default::StateQuotation> "PUBLISHED" and
        .job.payer.id = <std::uuid> $payer_id
        set {
            state := <default::StateQuotation> "APPROVED"
        }\
        """,
        quotation_id=quotation_id,
        payer_id=payer_id,
    )
