# AUTOGENERATED FROM 'queries/quotation_insert.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb:1234@localhost:10700 --tls-security insecure


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class QuotationInsertResult(NoPydanticValidation):
    id: uuid.UUID


async def quotation_insert(
    executor: edgedb.AsyncIOExecutor,
    *,
    job_id: uuid.UUID,
    quotation_description: str,
    quotation_total_amount: float,
    destine_id: uuid.UUID,
    delta_days: int,
) -> QuotationInsertResult:
    return await executor.query_single(
        """\
        INSERT Quotation {
            job := (SELECT Job FILTER .id = <std::uuid> $job_id),
            description := <std::str> $quotation_description,
            total_amount := <std::float64> $quotation_total_amount,
            destine := (SELECT User FILTER .id = <std::uuid> $destine_id),
            delta_days := <std::int32> $delta_days
        }\
        """,
        job_id=job_id,
        quotation_description=quotation_description,
        quotation_total_amount=quotation_total_amount,
        destine_id=destine_id,
        delta_days=delta_days,
    )
