# AUTOGENERATED FROM 'queries/quotation_save_escrow_finished_xumm_payload_uuid.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb:1234@localhost:10703 --tls-security insecure


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class QuotationSaveEscrowFinishedXummPayloadUuidResult(NoPydanticValidation):
    id: uuid.UUID


async def quotation_save_escrow_finished_xumm_payload_uuid(
    executor: edgedb.AsyncIOExecutor,
    *,
    quotation_id: uuid.UUID,
    destine_id: uuid.UUID,
    finished_xumm_payload_uuid: str,
) -> QuotationSaveEscrowFinishedXummPayloadUuidResult | None:
    return await executor.query_single(
        """\
        update default::Quotation 
        filter .id = <std::uuid> $quotation_id and .destine.id = <std::uuid> $destine_id 
        set {
          escrow_finished_xumm_payload_uuid := <std::str> $finished_xumm_payload_uuid,
          escrow_state := <default::StateQuotationEscrow> "WAITING_XUMM_SIGN_FINISH"
        }\
        """,
        quotation_id=quotation_id,
        destine_id=destine_id,
        finished_xumm_payload_uuid=finished_xumm_payload_uuid,
    )
