# AUTOGENERATED FROM 'queries/quotation_update_done.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb:1234@localhost:10703 --tls-security insecure


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class QuotationUpdateDoneResult(NoPydanticValidation):
    id: uuid.UUID


async def quotation_update_done(
    executor: edgedb.AsyncIOExecutor,
    *,
    quotation_id: uuid.UUID,
    destine_id: uuid.UUID,
) -> QuotationUpdateDoneResult | None:
    return await executor.query_single(
        """\
        UPDATE Quotation 
        filter .id = <std::uuid> $quotation_id and
        .state = <default::StateQuotation> "APPROVED" and
        .destine.id = <std::uuid> $destine_id
        set {
            state := <default::StateQuotation> "DONE" 
        }\
        """,
        quotation_id=quotation_id,
        destine_id=destine_id,
    )
