# AUTOGENERATED FROM 'queries/quotation_save_escrow_after_checked.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb:1234@localhost:10700 --tls-security insecure


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class QuotationSaveEscrowAfterCheckedResult(NoPydanticValidation):
    id: uuid.UUID


async def quotation_save_escrow_after_checked(
    executor: edgedb.AsyncIOExecutor,
    *,
    quotation_id: uuid.UUID,
    payer_id: uuid.UUID,
    escrow_txid: str,
    escrow_sequence: int,
) -> QuotationSaveEscrowAfterCheckedResult | None:
    return await executor.query_single(
        """\
        update default::Quotation 
        filter .id = <std::uuid> $quotation_id and .job.payer.id = <std::uuid> $payer_id 
        set {
          escrow_txid := <std::str> $escrow_txid,
          escrow_sequence := <std::int64> $escrow_sequence,
          escrow_state := <default::StateQuotationEscrow> "CHECKED",
          escrow_checked_at := datetime_of_statement()
        }\
        """,
        quotation_id=quotation_id,
        payer_id=payer_id,
        escrow_txid=escrow_txid,
        escrow_sequence=escrow_sequence,
    )
