# AUTOGENERATED FROM 'queries/quotation_select.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb:1234@localhost:10700 --tls-security insecure


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class QuotationSelectResult(NoPydanticValidation):
    id: uuid.UUID
    description: str
    total_amount: float
    destine: QuotationSelectResultDestine
    job: QuotationSelectResultJob


@dataclasses.dataclass
class QuotationSelectResultDestine(NoPydanticValidation):
    id: uuid.UUID
    name: str | None


@dataclasses.dataclass
class QuotationSelectResultJob(NoPydanticValidation):
    id: uuid.UUID


async def quotation_select(
    executor: edgedb.AsyncIOExecutor,
    *,
    payer_id: uuid.UUID,
    job_id: uuid.UUID,
) -> list[QuotationSelectResult]:
    return await executor.query(
        """\
        select default::Quotation {
          id,
          description,
          total_amount,
          destine: {
            id,
            name
          },
          job : {
            id
          }
        } filter .job.payer.id = <std::uuid> $payer_id and
          .job.id = <std::uuid> $job_id\
        """,
        payer_id=payer_id,
        job_id=job_id,
    )
