# AUTOGENERATED FROM 'queries/select_jobs.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb:1234@localhost:10700 --tls-security insecure


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class SelectJobsResult(NoPydanticValidation):
    id: uuid.UUID


async def select_jobs(
    executor: edgedb.AsyncIOExecutor,
) -> list[SelectJobsResult]:
    return await executor.query(
        """\
        select default::Job {
          id
        }\
        """,
    )
