# AUTOGENERATED FROM 'queries/user_select_profile_priv.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb:1234@localhost:10703 --tls-security insecure


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UserSelectProfilePrivResult(NoPydanticValidation):
    id: uuid.UUID
    public_address: str
    email: str | None
    name: str | None
    last_name: str | None
    full_address: str | None
    city: str | None
    postal_code: str | None
    country: str | None
    phone: str | None
    bio: str | None


async def user_select_profile_priv(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
) -> UserSelectProfilePrivResult | None:
    return await executor.query_single(
        """\
        select default::User {
          id,
          public_address,
          email,
          name,
          last_name,
          full_address,
          city,
          postal_code,
          country,
          phone,
          bio
        } filter .id = <std::uuid> $user_id\
        """,
        user_id=user_id,
    )
