# AUTOGENERATED FROM 'queries/user_update_profile.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb:1234@localhost:10700 --tls-security insecure


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UserUpdateProfileResult(NoPydanticValidation):
    id: uuid.UUID


async def user_update_profile(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
    email: str,
    name: str,
    last_name: str,
    full_address: str,
    city: str,
    postal_code: str,
    country: str,
    phone: str,
    bio: str,
) -> UserUpdateProfileResult | None:
    return await executor.query_single(
        """\
        update default::User 
        filter .id = <std::uuid> $user_id
        set {
          email := <std::str> $email,
          name := <std::str> $name,
          last_name := <std::str> $last_name,
          full_address := <std::str> $full_address,
          city := <std::str> $city,
          postal_code := <std::str> $postal_code,
          country := <std::str> $country,
          phone := <std::str> $phone,
          bio := <std::str> $bio,
        }\
        """,
        user_id=user_id,
        email=email,
        name=name,
        last_name=last_name,
        full_address=full_address,
        city=city,
        postal_code=postal_code,
        country=country,
        phone=phone,
        bio=bio,
    )
