# AUTOGENERATED FROM 'queries/user_register.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb:1234@localhost:10700 --tls-security insecure


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UserRegisterResult(NoPydanticValidation):
    id: uuid.UUID


async def user_register(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_address: str,
    initial_name: str,
) -> UserRegisterResult:
    return await executor.query_single(
        """\
        INSERT User {
            public_address := <std::str> $user_address,
            name := <std::str> $initial_name
        }\
        """,
        user_address=user_address,
        initial_name=initial_name,
    )
