# AUTOGENERATED FROM 'queries/user_select.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb:1234@localhost:10703 --tls-security insecure


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UserSelectResult(NoPydanticValidation):
    id: uuid.UUID
    email: str | None


async def user_select(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_address: str,
) -> list[UserSelectResult]:
    return await executor.query(
        """\
        select default::User {
          id,
          email
        } filter .public_address = <std::str> $user_address\
        """,
        user_address=user_address,
    )
