# AUTOGENERATED FROM 'queries/user_select_profile_priv.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb:1234@localhost:10701 --tls-security insecure


from __future__ import annotations
import dataclasses
import edgedb
import typing
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UserSelectProfilePrivResult(NoPydanticValidation):
    id: uuid.UUID
    public_address: str
    email: typing.Optional[str]
    name: typing.Optional[str]
    last_name: typing.Optional[str]
    full_address: typing.Optional[str]
    city: typing.Optional[str]
    postal_code: typing.Optional[str]
    country: typing.Optional[str]
    phone: typing.Optional[str]
    bio: typing.Optional[str]


async def user_select_profile_priv(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
) -> typing.Optional[UserSelectProfilePrivResult]:
    return await executor.query_single(
        """\
        select default::User {
          id,
          public_address,
          email,
          name,
          last_name,
          full_address,
          city,
          postal_code,
          country,
          phone,
          bio
        } filter .id = <std::uuid> $user_id\
        """,
        user_id=user_id,
    )
