# AUTOGENERATED FROM 'queries/user_select_profile.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb:1234@localhost:10701 --tls-security insecure


from __future__ import annotations
import dataclasses
import edgedb
import typing
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UserSelectProfileResult(NoPydanticValidation):
    id: uuid.UUID
    name: typing.Optional[str]
    last_name: typing.Optional[str]
    country: typing.Optional[str]
    bio: typing.Optional[str]


async def user_select_profile(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
) -> typing.Optional[UserSelectProfileResult]:
    return await executor.query_single(
        """\
        select default::User {
          id,
          name,
          last_name,
          country,
          bio
        } filter .id = <std::uuid> $user_id\
        """,
        user_id=user_id,
    )
